include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    no_default_cases: false
    one_member_abstracts: false
    avoid_positional_boolean_parameters: false
