name: snip_and_style
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.5.0
  bloc: ^8.1.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  intl: ^0.18.0


dev_dependencies:
  auto_route_generator: ^7.1.1   
  bloc_test: ^9.1.2
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0


flutter_gen:
  output: lib/config/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/