name: Android Build and Deploy

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: "Manually release"

jobs:
  build-and-deploy:
    name: Build and Deploy Android App
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16" # specify the Flutter version

      - name: Set Up Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Authenticate with Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase login --interactive --token $FIREBASE_TOKEN

      # Build and Deploy Android App
      - name: Execute Fastlane Lane
        working-directory: android
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_GROUPS: ${{ secrets.FIREBASE_GROUPS }}
        run: |
          bundle exec fastlane android development
