name: Android Build and Deploy

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: "Manually release"

env:
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
  KEYSTORE: ${{ secrets.KEYSTORE }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  FIREBASE_GROUPS: ${{ secrets.FIREBASE_GROUPS }}
  ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
  ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
  ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

jobs:
  build-and-deploy:
    name: Build and Deploy Android App
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16"

      - name: Create .env File
        run: |
          touch .env

      - name: Decode Google Services JSON
        working-directory: android/app
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > google-services.json

      - name: Set Up Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Authenticate with Firebase
        run: firebase login --no-localhost --interactive --token $FIREBASE_TOKEN

      - name: Decode Keystore File
        working-directory: android
        run: |
          echo "$KEYSTORE" | base64 -d > key.jks

      - name: Execute Fastlane Lane
        working-directory: android
        run: |
          bundle exec fastlane android development
